// localhost

###
GET http://localhost:3000/employees

###
GET http://localhost:3000/employees/6453a4e8539a09ae277873e5

### Create employee
POST http://localhost:3000/employees HTTP/1.1
Content-Type: application/json

{
"firstName":"Joseph",
"lastName": "Williams",
"email":"seven@email.com",
"favoriteColor":"home",
"birthday":"2063-01-01T08:00:00.000Z",
"password":"Abc123!1"
}

# {
# "firstName":"David",
# "lastName": "Paich",
# "email":"tambu@email.com",
# "favoriteColor":"moonlit",
# "birthday":"2023-01-01T08:00:00.000Z",
# "password":"Abc123!1"
# }

# {
#         "firstName":"Jeff",
#     "lastName":"Porcaro",
#     "email":"skins@email.com",
#     "favoriteColor":"cocoa",
#     "birthday": "2023-07-04",
#       "password":""
# }
# {
#     "firstName":"Mike",
#     "lastName":"Porcaro",
#     "email":"stringsoffour@email.com",
#     "favoriteColor":"brown",
#     "birthday":"2023-12-25T08:00:00.000Z",
#       "password":""
# }

### PUT employee
PUT http://localhost:3000/employees/6453afc77c08df2a678077f4
Content-Type: application/json

{
    "firstName":"David",
    "lastName":"Paich",
    "email":"hurryboy@email.com",
    "favoriteColor":"tambu",
    "birthday":"2023-01-01T08:00:00.000Z",
    "password":"Abc123!1"
}



###
DELETE http://localhost:3000/employees/6453afc77c08df2a678077f4





// ================Production deployment=======================================
###
GET https://web-service-final341.onrender.com/employees

###
GET https://web-service-final341.onrender.com/employees/6453a4e8539a09ae277873e5

### Create employee
POST https://web-service-final341.onrender.com/employees HTTP/1.1
Content-Type: application/json

{
"firstName":"David",
"lastName": "Paich",
"email":"tambu@email.com",
"favoriteColor":"moonlit",
"birthday":"2023-01-01T08:00:00.000Z",
"password":"Abc123!1"
}

# {
#     "firstName":"Jeff",
#     "lastName":"Porcaro",
#     "email":"skins@email.om",
#     "favoriteColor":"cocoa",
#     "birthday": "2023-07-04",
#     "password":"Abc123!1"
# }

### PUT employee
PUT https://web-service-final341.onrender.com/employees/6453afc77c08df2a678077f4

{
    "firstName":"David",
    "lastName":"Paich",
    "email":"tambu@email.om",
    "favoriteColor":"moonlit",
    "birthday":"2023-01-01T08:00:00.000Z",
    "password":"Abc123!1"
}

###
DELETE https://web-service-final341.onrender.com/employees/6453afc77c08df2a678077f4

